openapi: 3.0.1
info:
  title: Car Rental API
  description: API for managing car rentals
  version: 1.0.0
paths:
  /cars:
    get:
      summary: Get all cars
      responses:
        '200':
          description: A list of cars
  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: A list of customers
  /rentals:
    get:
      summary: Get all rentals
      responses:
        '200':
          description: A list of rentals